version: '3.4'

services:
  backend:
    image: ${DOCKER_REGISTRY-}organizerbackendnet
    build:
      context: .
      dockerfile: organizer-backend-NET/Dockerfile
  client:
    image: client
    build:
        context: ./Client
        dockerfile: Dockerfile
  proxy:
    image: nginx:mainline

  db:
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=localhost
      - POSTGRES_DATABASE=organizer 
