version: '3.5'

services:
  organizer:
    container_name: organizer.NET
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
      - POSTGRES_HOST=localhost
      - POSTGRES_DATABASE=organizer
    image: postgres:15.1-bullseye
